### ISSUE TITLE
Speed Up Model by Using cudnn benchmark

### ISSUE THREAD

**Issue by davidrzs** [yaohungt/Barlow-Twins-HSIC#2]
Not really an issue, but adding the following made training significantly faster (+29% on Titan X Pascal)
```
if torch.cuda.is_available():
    torch.backends.cudnn.benchmark = True
```
I thought I would mention it as others might benefit from this as well.

Thanks for making your code available on GitHub!

**Comment by yaohungt** [comment]
Thanks!
